In [1]:
import numpy as np
import pandas as pd

In [12]:
arr = np.array([[1,2,3,4,5,6], [23,5,6,7,8,9]])
print(arr)

[[ 1  2  3  4  5  6]
 [23  5  6  7  8  9]]


In [8]:
print(len(arr))
print(arr.ndim)
print(arr.shape)
print(arr.nbytes)

2
2
(2, 6)
48


In [33]:
arr1 = np.arange(12, dtype=int).reshape(2,6)
print(arr1)
print(np.mean(arr1))
print(round(np.std(arr1), 2))
print(np.power(arr, arr1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
5.5
3.45
[[         1          2          9         64        625       7776]
 [ 148035889      78125    1679616   40353607 1073741824 1316288537]]
